# Application
spring:
  config:
    encoding: UTF-8
  application:
    name: pos-connector

server:
  port: 8080

# logging
logging:
  file:
    name: logs/pos-connector.log
  level:
    root: INFO
    bg.logicsoft.pos_connector: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 50
      file-name-pattern: logs/pos-connector-%d{yyyy-MM-dd}.%i.log

# ERPNext
erpnext:
  url: "http://10.0.204.174"
  api-key: "cb02af5931214ce"
  api-secret: "101a8ace09f0ff1"

  # Sales Invoice details
  pos-profile: "pos profile EUR"
  charge-type: "On Net Total"

  # Employee - Cashiers
  employee:
    designation: "POS cashier"

# Fiscal Printer Gate
fpgate:
  url: "http://localhost:8182"