# Application
spring:
  config:
    encoding: UTF-8
  application:
    name: pos-connector

server:
  port: 8080

# ERPNext
erpnext:
  url: "http://10.0.204.174"
  api-key: "cb02af5931214ce"
  api-secret: "101a8ace09f0ff1"

  # Sales Invoice details
  pos-warehouse: "POS Склад 1 - L"
  #pos-profile-BGN: "POS profile BGN"
  pos-profile-EUR: "pos profile EUR"
  #mode-of-payment-BGN: "Cash BGN"
  mode-of-payment-EUR: "Cash EUR" # ?!?!?!?!?!?!
  #price-list-BGN: "pos sales BGN"
  price-list-EUR: "pos sales EUR"
  company: "LogicSoft"
  #debit-to-BGN: "1310 - Debtors - L"
  debit-to-EUR: "1311 - Debtors EUR - L" # ?!?!?!?!?!?!
  charge-type: "On Net Total"   # TODO: probably should be for every row
  currency: "EUR"

  # Employee - Cashiers
  employee:
    designation: "POS cashier"

# Fiscal Printer Gate
fpgate:
  url: "http://localhost:8182"