# Application
spring:
  config:
    encoding: UTF-8
  application:
    name: pos-connector

server:
  port: 8080

# ERPNext
erpnext:
  url: "http://site15.local:8001"
  api-key: "0175434ef147c4b"
  api-secret: "afede6137335392"

  # Sales Invoice details
  pos-warehouse: "POS Склад 2 - CE2"
  pos-profile-EUR: "POS profile EUR"
  price-list-EUR: "pos sales EUR"
  company: "Company-2 EUR"
  debit-to-EUR: "Debtors - CE2" # ?!?!?!?!?!?!
  charge-type: "On Net Total"   # TODO: probably should be for every row
  currency: "EUR"

  # Employee - Cashiers
  employee:
    designation: "POS cashier"

# Fiscal Printer Gate
fpgate:
  url: "http://localhost:8182"